version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
jobs:
  release:
    docker:
      - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/SuperComplex/
      - run:
          name: Build Solution
          command: dotnet build ./src/SuperComplex/
      - run:
          name: Test Solution
          command: dotnet test ./src/SuperComplex/
  qa:
    docker:
      - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/SuperComplex/
      - run:
          name: Build Solution
          command: dotnet build ./src/SuperComplex/
      - run:
          name: Test Solution
          command: dotnet test ./src/SuperComplex/
  dev:
    docker:
    - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/SuperComplex/
      - run:
          name: Build Solution
          command: dotnet build ./src/SuperComplex/
      - run:
          name: Test Solution
          command: dotnet test ./src/SuperComplex/
      - sonarcloud/scan
workflows:
  version: 2
  build_test_dev:
    jobs:
      - dev:
         context: sonarcloud
