name: approved workflow
on:
  pull_request:
   types:
    - labeled
jobs:
  read_for_review_pr_job:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    name: Run Code Coverage
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet build ./src/SuperComplex/
    - run: dotnet test ./src/SuperComplex/
